import React from 'react';
import styled from 'styled-components';
import { Link } from 'react-router-dom';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';
import { FaDumbbell, FaUtensils, FaChartLine, FaRobot } from 'react-icons/fa';

const HomeContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: 2rem 0;
`;

const HeroSection = styled.div`
  margin-bottom: 3rem;
  max-width: 800px;
  padding: 0 1rem;
`;

const HeroTitle = styled.h1`
  font-size: ${props => props.theme.fontSizes['4xl']};
  margin-bottom: 1rem;
`;

const HeroSubtitle = styled.p`
  font-size: ${props => props.theme.fontSizes.xl};
  color: rgba(45, 55, 72, 0.8);
  margin-bottom: 2rem;
`;

const FeaturesContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 2rem;
  width: 100%;
  max-width: 1200px;
  padding: 0 1rem;
  margin-bottom: 3rem;
`;

const FeatureCard = styled(Card)`
  transition: transform 0.3s ease;
  
  &:hover {
    transform: translateY(-5px);
  }
`;

const FeatureIcon = styled.div`
  width: 60px;
  height: 60px;
  border-radius: 50%;
  background: ${props => props.theme.colors.background};
  box-shadow: ${props => props.theme.shadows.neuFlat};
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 1.5rem;
  color: ${props => props.theme.colors.primary};
`;

const FeatureTitle = styled.h3`
  font-size: ${props => props.theme.fontSizes.xl};
  margin-bottom: 1rem;
`;

const AIDisclaimer = styled.div`
  background: ${props => props.theme.colors.background};
  box-shadow: ${props => props.theme.shadows.neuInset};
  border-radius: ${props => props.theme.radii.md};
  padding: 1.5rem;
  max-width: 800px;
  margin: 0 auto 3rem;
`;

const CTASection = styled.div`
  text-align: center;
  margin-bottom: 3rem;
`;

const HomePage = () => {
  return (
    <HomeContainer>
      <HeroSection>
        <HeroTitle>Transform Your Fitness Journey with AI</HeroTitle>
        <HeroSubtitle>
          Get personalized workout and nutrition plans tailored to your unique goals and preferences.
        </HeroSubtitle>
        <Button 
          as={Link} 
          to="/dashboard" 
          variant="primary" 
          size="large"
        >
          Get Started
        </Button>
      </HeroSection>
      
      <FeaturesContainer>
        <FeatureCard>
          <FeatureIcon>
            <FaDumbbell size={25} />
          </FeatureIcon>
          <FeatureTitle>Personalized Workouts</FeatureTitle>
          <p>
            Get AI-generated workout plans tailored to your fitness level, goals, and available equipment.
            Never wonder what to do at the gym again.
          </p>
        </FeatureCard>
        
        <FeatureCard>
          <FeatureIcon>
            <FaUtensils size={25} />
          </FeatureIcon>
          <FeatureTitle>Custom Meal Plans</FeatureTitle>
          <p>
            Receive nutrition plans that align with your goals and dietary preferences.
            Meet your calorie and macro targets with delicious meal options.
          </p>
        </FeatureCard>
        
        <FeatureCard>
          <FeatureIcon>
            <FaChartLine size={25} />
          </FeatureIcon>
          <FeatureTitle>Progress Tracking</FeatureTitle>
          <p>
            Track your weight, body measurements, and workout performance over time.
            Visualize your progress and stay motivated.
          </p>
        </FeatureCard>
        
        <FeatureCard>
          <FeatureIcon>
            <FaRobot size={25} />
          </FeatureIcon>
          <FeatureTitle>AI-Powered</FeatureTitle>
          <p>
            Leverage cutting-edge AI models to generate fitness and nutrition recommendations
            based on the latest scientific research and best practices.
          </p>
        </FeatureCard>
      </FeaturesContainer>
      
      <AIDisclaimer>
        <h3>Important Health Disclaimer</h3>
        <p>
          The fitness and nutrition plans generated by this application are created by artificial intelligence
          and should not be considered medical advice. Please consult with your healthcare provider before
          starting any new fitness program or making significant changes to your diet, especially if you
          have pre-existing health conditions.
        </p>
      </AIDisclaimer>
      
      <CTASection>
        <h2>Ready to transform your fitness journey?</h2>
        <p>Take the first step toward your health and fitness goals today.</p>
        <Button 
          as={Link} 
          to="/dashboard" 
          variant="primary" 
          size="large" 
          margin="1rem 0 0"
        >
          Get Started Now
        </Button>
      </CTASection>
    </HomeContainer>
  );
};

export default HomePage;
